describe("glossator-nvim", function()
  it("module loads without error", function()
    assert.has.no.errors(function()
      require("glossator-nvim")
    end)
  end)

  it("has public API functions", function()
    local m = require("glossator-nvim")
    assert.is_function(m.setup)
    assert.is_function(m.load_highlights)
    assert.is_function(m.open_toolbar)
    assert.is_function(m.open_glossator)
  end)

  it("defaults are returned by config module", function()
    local defaults = require("glossator-nvim.config.defaults")
    assert.is_table(defaults.hl_tags)
    assert.are.equal(5, #defaults.hl_tags)
    assert.is_table(defaults.ul_tags)
    assert.are.equal(5, #defaults.ul_tags)
    assert.is_table(defaults.toolbar_hl)
    assert.is_table(defaults.fmt_actions)
    assert.are.equal(3, #defaults.fmt_actions)
    assert.is_table(defaults.par_actions)
    assert.are.equal(5, #defaults.par_actions)
    assert.is_string(defaults.notes_dir)
  end)

  describe("setup", function()
    it("accepts empty opts", function()
      local m = require("glossator-nvim")
      assert.has.no.errors(function()
        m.setup({})
      end)
    end)

    it("merges user config with defaults", function()
      local m = require("glossator-nvim")
      m.setup({
        hl_tags = {
          { key = "x", tag = "[hx]", group = "ETCustom", hl = { bg = "#ff0000", fg = "#ffffff" } },
        },
      })
      -- After setup, open_toolbar should work
      assert.has.no.errors(function()
        vim.cmd("enew")
        vim.cmd("set ft=markdown")
        m.load_highlights()
      end)
    end)
  end)

  describe("health check", function()
    it("runs without error", function()
      local health = require("glossator-nvim.health")
      assert.has.no.errors(function()
        health.check()
      end)
    end)
  end)
end)
